apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: demo-nginx
    version: v0.0.1
  name: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      application: demo-nginx
  template:
    metadata:
      labels:
        application: demo-nginx
        version: v0.0.1
    spec:
      containers:
      - name: service
        image: theopenbit/rpi-demo-nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
