apiVersion: v1
kind: Service
metadata:
  labels:
    application: demo-nginx
  name: demo-nginx
spec:
  selector:
    application: demo-nginx
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
